name: Test Suite
on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  tests:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - name: mergestat/mergestat
          - name: kubernetes/kubernetes
          - name: facebook/react
          - name: torvalds/linux
            blameFilePath: README

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.1
        id: go

      - name: Check out source
        uses: actions/checkout@v4

      - name: Check out source
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo.name }}
          path: .repo
          fetch-depth: 0

      - name: Test
        run: make test
        env:
          REPO_PATH: ${{github.workspace}}/.repo
          BLAME_FILE_PATH: ${{ matrix.repo.blameFilePath }}
